### PR TITLE
Deposit

### PR DESCRIPTION
**Pull request by TheTDD**
As requested. There is some disorder with the files, please merge only my changes (w/o merge from development).

### CODE REVIEW

**Comment by ghobson2013** [comment]
56 commits, that doesnt look correct to me,  what happened to the 11 files changed ?
dev-1.1.4 was branched of master branch, because i plan to delete and recreate the dev branch.

**Comment by TheTDD** [comment]
Can you accept pull request to development branch and then merge only particular commits to dev-1.4 branch:

https://www.hacksparrow.com/how-to-merge-a-specific-commit-in-git.html

**Comment by TheTDD** [comment]
These commits should be merged:

c3d7b89
b00a7cc
9dfe2ae
e7974a0
59417cf
b46c43f

**Comment by ghobson2013** [comment]
Yes i will merge manually.

**Comment by ghobson2013** [comment]
will merge manually from PR 44

**Pull request closed without merging**
